<?php
include("header.php");
?>

<section class="l-section wpb_row height_small with_shape ult-vc-hide-row vc_row-has-fill" id="nahve-ejra" data-rtl="true" style="position: relative;" data-row-effect-mobile-disable="true"><div class="upb_row_bg" data-bg-override="0" style="background: rgba(16, 150, 244, 0.15); min-width: 1404px; right: 0px; width: 1403px;"></div><div class="l-section-shape type_curve pos_bottom" style="height:2vh;"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 8" preserveAspectRatio="none" width="100%" height="100%">
	<path fill="currentColor" d="M64 8 L64 0 Q32 15.8 0 0 L0 8 Z"></path>
</svg></div><div class="l-section-h i-cf"><div class="g-cols vc_row via_flex valign_top type_default stacking_default"><div class="vc_col-sm-6 wpb_column vc_column_container"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="w-hwrapper align_right valign_baseline" style="--hwrapper-gap:3px"><div class="wpb_text_column us_custom_a74da290"><div class="wpb_wrapper"><h2><span style="color: #f7861c;" ><strong>نحوه اجرای حرکت</strong></span></h2>
</div></div><h2 class="w-post-elm post_title us_custom_649605bd has_text_color entry-title color_link_inherit">جلو بازو لاری هالتر EZ</h2><div class="w-post-elm post_custom_field type_text ejraye_harekat">
<ol class=" fs-5 text">
<li>برای شروع روی میز جلو بازو لاری بنشینید و دستان خود را به اندازه عرض شانه به هالتر بگیرید و در حالتی که شانه را بالا می گیرید و قوس کمر را حفظ می کنید هالتر را بردارید.</li>
<li>هالتر را به سمت بالا (صورت) بیاورید تا انقباض کامل ایجاد شود، دست باید تقریبا روبروی صورت قرار بگیرد. این بخش فاز مثبت حرکت بوده و در این فاز عمل بازدم را انجام دهید.</li>
<li>سپس هالتر را به سمت حالت اولیه برگردانید تا دست‌ها باز شوند البته کمی مانده به کامل باز شدن. این بخش، فاز منفی حرکت بوده و در این فاز دم را انجام دهید.</li>
<li>حرکت را به تعداد مشخص در برنامه خود تکرار کنید.</li>
</ol>
<p class="fs-5 text">حفظ فرم باسن و کمر در هنگام انجام حرکات با میز لاری حائز اهمیت است.</p>
</div></div></div></div></div><div class="vc_col-sm-6 vc_col-lg-offset-0 wpb_column vc_column_container"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="w-post-elm post_custom_field us_custom_0b155626 type_image image_ejraye_harekat has_border_radius"><img width="400" height="300" src="img/Z-Bar-Preacher-Curl12-1.gif"><img width="400" height="300" alt="ناحیه فشار عضله در حرکت جلو بازو لاری هالتر EZ" decoding="async" data-srcset="https://fitshim.com/wp-content/uploads/2020/07/lari-halter-jolo-bazoo-muscles-worked.jpg 400w, https://fitshim.com/wp-content/uploads/2020/07/lari-halter-jolo-bazoo-muscles-worked-300x225.jpg 300w, https://fitshim.com/wp-content/uploads/2020/07/lari-halter-jolo-bazoo-muscles-worked-24x18.jpg 24w, https://fitshim.com/wp-content/uploads/2020/07/lari-halter-jolo-bazoo-muscles-worked-36x27.jpg 36w, https://fitshim.com/wp-content/uploads/2020/07/lari-halter-jolo-bazoo-muscles-worked-48x36.jpg 48w" data-src="https://fitshim.com/wp-content/uploads/2020/07/lari-halter-jolo-bazoo-muscles-worked.jpg" data-sizes="(max-width: 400px) 100vw, 400px" class="attachment-full size-full lazyloaded" src="https://fitshim.com/wp-content/uploads/2020/07/lari-halter-jolo-bazoo-muscles-worked.jpg" sizes="(max-width: 400px) 100vw, 400px" srcset="https://fitshim.com/wp-content/uploads/2020/07/lari-halter-jolo-bazoo-muscles-worked.jpg 400w, https://fitshim.com/wp-content/uploads/2020/07/lari-halter-jolo-bazoo-muscles-worked-300x225.jpg 300w, https://fitshim.com/wp-content/uploads/2020/07/lari-halter-jolo-bazoo-muscles-worked-24x18.jpg 24w, https://fitshim.com/wp-content/uploads/2020/07/lari-halter-jolo-bazoo-muscles-worked-36x27.jpg 36w, https://fitshim.com/wp-content/uploads/2020/07/lari-halter-jolo-bazoo-muscles-worked-48x36.jpg 48w"><noscript><img width="400" height="300" src="https://fitshim.com/wp-content/uploads/2020/07/lari-halter-jolo-bazoo-muscles-worked.jpg" class="attachment-full size-full" alt="ناحیه فشار عضله در حرکت جلو بازو لاری هالتر EZ" decoding="async" srcset="https://fitshim.com/wp-content/uploads/2020/07/lari-halter-jolo-bazoo-muscles-worked.jpg 400w, https://fitshim.com/wp-content/uploads/2020/07/lari-halter-jolo-bazoo-muscles-worked-300x225.jpg 300w, https://fitshim.com/wp-content/uploads/2020/07/lari-halter-jolo-bazoo-muscles-worked-24x18.jpg 24w, https://fitshim.com/wp-content/uploads/2020/07/lari-halter-jolo-bazoo-muscles-worked-36x27.jpg 36w, https://fitshim.com/wp-content/uploads/2020/07/lari-halter-jolo-bazoo-muscles-worked-48x36.jpg 48w" sizes="(max-width: 400px) 100vw, 400px" /></noscript></div></div></div></div></div></div></section>
  
<?php
include("footer.html");
?>