<?php
include("header.html");
?>


<section class="l-section wpb_row height_small with_shape ult-vc-hide-row vc_row-has-fill" id="nahve-ejra" data-rtl="true" data-row-effect-mobile-disable="true" style="position: relative;"><div class="upb_row_bg" data-bg-override="0" style="background: rgba(16, 150, 244, 0.15); min-width: 1348px; right: 0px; width: 1347px;"></div><div class="l-section-shape type_curve pos_bottom" style="height:2vh;"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 8" preserveAspectRatio="none" width="100%" height="100%">
	<path fill="currentColor" d="M64 8 L64 0 Q32 15.8 0 0 L0 8 Z"></path>
</svg></div><div class="l-section-h i-cf"><div class="g-cols vc_row via_flex valign_top type_default stacking_default"><div class="vc_col-sm-6 wpb_column vc_column_container"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="w-hwrapper align_right valign_baseline" style="--hwrapper-gap:3px"><div class="wpb_text_column us_custom_a74da290"><div class="wpb_wrapper"><h2><span style="color: #f7861c;"><strong>نحوه اجرای حرکت</strong></span></h2>
</div></div><h2 class="w-post-elm post_title us_custom_649605bd has_text_color entry-title color_link_inherit">زیر بغل سیم کش از جلو دست باز</h2><div class="w-post-elm post_custom_field type_text ejraye_harekat"><ol>
<li>ابتدا دست‌ها را بر روی میله دستگاه به گونه‌ای تنظیم کنید که تا کاملا قرینه باشند. در نظر داشته باشید که می‌توان از گیرش‌های مختلف برای گرفتن میله استفاده کرد.</li>
<li>روی صندلی دستگاه بنشینید و زانو را زیر جاپایی قرار دهید ، به گونه‌ای که زاویه زانو و کمر ۹۰ درجه باشد.</li>
<li>حرکت را با رعایت قوس کمر مناسب ، شروع کنید. به گونه‌ای که دستگیره تا نزدیک سینه پایین کشیده شود ، تا انقباض کامل صورت گیرد. این قسمت از تمرین ، فاز مثبت است. در این بخش ، عمل بازدم را انجام دهید.</li>
<li>دستگیره را با کنترل کامل و تمرکز و با سرعت مورد نظر ، به نقطه اولیه حرکت بازگردانید. این قسمت از تمرین ، فاز منفی است. در این بخش ، عمل دم را انجام دهید.</li>
<li>این کار را به تعداد مشخص شده در برنامه خود تکرار کنید.</li>
</ol>
<p>تمرین را ۴ در فاز مثبت و ۴ در فاز مثبت و تکنیک صحیح انجام دهید تا تاثیر مورد نظر را بر عضله بگذارد.</p>
</div></div></div></div></div><div class="vc_col-sm-6 vc_col-lg-offset-0 wpb_column vc_column_container"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="w-post-elm post_custom_field us_custom_0b155626 type_image image_ejraye_harekat has_border_radius"><img src="img/Wide-grip-lat-pulldown.gif" ><img width="400" height="300" alt="عضلات درگیر زیر بغل سیم کش از جلو دست باز" decoding="async" data-srcset="https://fitshim.com/wp-content/uploads/2021/04/wide-grip-lat-pull-down-muscles-worked.jpg 400w, https://fitshim.com/wp-content/uploads/2021/04/wide-grip-lat-pull-down-muscles-worked-300x225.jpg 300w, https://fitshim.com/wp-content/uploads/2021/04/wide-grip-lat-pull-down-muscles-worked-24x18.jpg 24w, https://fitshim.com/wp-content/uploads/2021/04/wide-grip-lat-pull-down-muscles-worked-36x27.jpg 36w, https://fitshim.com/wp-content/uploads/2021/04/wide-grip-lat-pull-down-muscles-worked-48x36.jpg 48w" data-src="https://fitshim.com/wp-content/uploads/2021/04/wide-grip-lat-pull-down-muscles-worked.jpg" data-sizes="(max-width: 400px) 100vw, 400px" class="attachment-full size-full ls-is-cached lazyloaded" src="https://fitshim.com/wp-content/uploads/2021/04/wide-grip-lat-pull-down-muscles-worked.jpg" sizes="(max-width: 400px) 100vw, 400px" srcset="https://fitshim.com/wp-content/uploads/2021/04/wide-grip-lat-pull-down-muscles-worked.jpg 400w, https://fitshim.com/wp-content/uploads/2021/04/wide-grip-lat-pull-down-muscles-worked-300x225.jpg 300w, https://fitshim.com/wp-content/uploads/2021/04/wide-grip-lat-pull-down-muscles-worked-24x18.jpg 24w, https://fitshim.com/wp-content/uploads/2021/04/wide-grip-lat-pull-down-muscles-worked-36x27.jpg 36w, https://fitshim.com/wp-content/uploads/2021/04/wide-grip-lat-pull-down-muscles-worked-48x36.jpg 48w"><noscript><img width="400" height="300" src="https://fitshim.com/wp-content/uploads/2021/04/wide-grip-lat-pull-down-muscles-worked.jpg" class="attachment-full size-full" alt="عضلات درگیر زیر بغل سیم کش از جلو دست باز" decoding="async" srcset="https://fitshim.com/wp-content/uploads/2021/04/wide-grip-lat-pull-down-muscles-worked.jpg 400w, https://fitshim.com/wp-content/uploads/2021/04/wide-grip-lat-pull-down-muscles-worked-300x225.jpg 300w, https://fitshim.com/wp-content/uploads/2021/04/wide-grip-lat-pull-down-muscles-worked-24x18.jpg 24w, https://fitshim.com/wp-content/uploads/2021/04/wide-grip-lat-pull-down-muscles-worked-36x27.jpg 36w, https://fitshim.com/wp-content/uploads/2021/04/wide-grip-lat-pull-down-muscles-worked-48x36.jpg 48w" sizes="(max-width: 400px) 100vw, 400px" /></noscript></div></div></div></div></div></div></section>

<?php
include("footer.html");
?>